version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: aviation_postgres
    environment:
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
      POSTGRES_DB: aviation_db
    ports:
    - 5432
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: